---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.anvil.host }}
  namespace: {{.Release.Namespace}}
  labels:
    app: anvil
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.anvil.port }}
      targetPort: {{ .Values.anvil.port }}
      nodePort: {{ .Values.anvil.nodeport }}
      name: shell
  selector:
    app: anvil
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
  namespace: {{.Release.Namespace}}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.anvil.replicas }}
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
    spec:
      serviceAccountName: {{ .Values.sa.anvil }}
      volumes:
      - name: anvilroot
        persistentVolumeClaim:
          claimName: anvil-local-claim
      containers:
      - image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: {{ .Values.nginx.max_mem }}
            cpu: {{ .Values.nginx.max_cpu }}
        ports:
        - containerPort: {{ .Values.anvil.port }}
        env:
        - name: HTPASSWD
          valueFrom:
            secretKeyRef:
              name: nginxsecret
              key: htpasswd
        command:
        - sh
        - -c
        - |
          cat <<EOF> /etc/nginx/conf.d/default.conf
          server {
            listen 80 default_server;

            location / {
              auth_basic            "Feed me passwords";
              auth_basic_user_file  auth.htpasswd;

              proxy_connect_timeout 7d;
              proxy_read_timeout    7d;
              proxy_send_timeout    7d;

              proxy_pass            http://localhost:5757;
              proxy_http_version    1.1;

              proxy_set_header      Host \$host;
              proxy_set_header      Upgrade \$http_upgrade;
              proxy_set_header      Connection "upgrade";
              proxy_set_header      Origin "\$scheme://\$host";
            }
          }
          EOF

          cat <<EOF> /etc/nginx/auth.htpasswd
          $HTPASSWD
          EOF

          nginx -g "daemon off;"
      - image: {{ .Values.anvil.image.name }}:{{ .Values.anvil.image.tag }}
        imagePullPolicy: IfNotPresent
        name: anvil
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: {{ .Values.anvil.max_mem }}
            cpu: {{ .Values.anvil.max_cpu }}
        ports:
        - containerPort: 5757
        command:
        - zsh
        - -c
        - |
          /root/entrypoint.sh \
            --proxy \
            --shell='{{ .Values.anvil.user.shell }}' \
            --fullname='{{ .Values.anvil.user.name }}' \
            --myemail='{{ .Values.anvil.user.email }}' \
            --pastebinurl='{{ .Values.anvil.user.repolist }}' \
            --giturlwithcred='{{ .Values.anvil.user.giturl }}'
        volumeMounts:
        - name: anvilroot
          mountPath: /root/repos
