---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cloud9.host }}
  namespace: {{.Release.Namespace}}
  labels:
    app: cloud9
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.cloud9.port }}
      targetPort: {{ .Values.cloud9.port }}
      nodePort: {{ .Values.cloud9.nodeport }}
      name: ide
  selector:
    app: cloud9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud9
  namespace: {{.Release.Namespace}}
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.cloud9.replicas }}
  selector:
    matchLabels:
      app: cloud9
  template:
    metadata:
      labels:
        app: cloud9
    spec:
      serviceAccountName: {{ .Values.sa.anvil }}
      volumes:
      - name: anvilroot
        persistentVolumeClaim:
          claimName: anvil-local-claim
      containers:
      - image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: {{ .Values.nginx.max_mem }}
            cpu: {{ .Values.nginx.max_cpu }}
        ports:
        - containerPort: {{ .Values.cloud9.port }}
        env:
        - name: HTPASSWD
          valueFrom:
            secretKeyRef:
              name: nginxsecret
              key: htpasswd
        command:
        - sh
        - -c
        - |
          cat <<EOF> /etc/nginx/conf.d/default.conf
          server {
            listen 80 default_server;

            location / {
              auth_basic            "Feed me passwords";
              auth_basic_user_file  auth.htpasswd;

              proxy_connect_timeout 7d;
              proxy_read_timeout    7d;
              proxy_send_timeout    7d;

              proxy_pass            http://localhost:8181;
              proxy_http_version    1.1;

              proxy_set_header      Host \$host;
              proxy_set_header      Upgrade \$http_upgrade;
              proxy_set_header      Connection "upgrade";
              proxy_set_header      Origin "\$scheme://\$host";
            }
          }
          EOF

          cat <<EOF> /etc/nginx/auth.htpasswd
          $HTPASSWD
          EOF

          nginx -g "daemon off;"
      - image: {{ .Values.cloud9.image.name }}:{{ .Values.cloud9.image.tag }}
        imagePullPolicy: IfNotPresent
        name: cloud9
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: {{ .Values.cloud9.max_mem }}
            cpu: {{ .Values.cloud9.max_cpu }}
        ports:
        - containerPort: 8181
        command:
        - "-a : "
        volumeMounts:
        - name: anvilroot
          mountPath: /workspace
